const categories = {
  incomingCategories: [
    'Account receivable',
    'Additional Income',
    'Allowance',
    'Bonus',
    'Business profit',
    'Capital Gain',
    'Income',
    'Incoming',
    'Interest',
    'Reimbursment',
    'Salary',
  ],
  outgoingCategories: [
    'Books',
    'Cable TV',
    'Cafe',
    'Cash withdrawal',
    'Charity & donation',
    'Children',
    'Cinema',
    'Cost & taxes',
    'Credit Card',
    'Doctor fee',
    'Domestic helper',
    'Drugs/ medicine',
    'Education',
    'Entertainment',
    'Fashion',
    'Food & Drinks',
    'Gadget & electronics',
    'Games',
    'Gas',
    'Gasoline',
    'Gifts',
    'Groceries',
    'Hang out',
    'Healthcare',
    'Hobby',
    'House & apartment rent',
    'Housing',
    'Insurance',
    'Investment',
    'Loans',
    'Mobile & Internet',
    'Others',
    'Outgoing',
    'Parking fee',
    'Personal care',
    'Pet',
    'Refund',
    'Renovation',
    'Restaurant',
    'Savings',
    'Sports',
    'Top up card',
    'Top up Wallet',
    'Transportation',
    'Utilities',
    'Vehicle maintenance',
    'Wedding',
  ],
}
export default categories;
